export const spots = [
  {
    id: 'tiananmen',
    name: '天安门',
    image: 'https://s.coze.cn/image/fL6_35wRNmw/',
    description: '北京中轴线的核心地标，明清两代皇城正门，也是中国国家象征之一。',
  },
  {
    id: 'forbidden-city',
    name: '故宫',
    image: 'https://s.coze.cn/image/GMtey0UpZlg/',
    description: '明清两代皇宫，又称紫禁城，世界现存规模最大的木结构古建筑群。',
  },
  {
    id: 'national-museum',
    name: '国家博物馆',
    image: 'https://s.coze.cn/image/FCmcT9L681M/',
    description: '中国最高历史文化艺术殿堂，馆藏文物极为丰富，陈列体系完整。',
  },
  {
    id: 'chairman-ma-memorial',
    name: '毛主席纪念堂',
    image: 'https://s.coze.cn/image/lu7cZWPNosc/',
    description: '位于天安门广场，缅怀伟人的庄严肃穆纪念场所。',
  },
  {
    id: 'great-hall',
    name: '人民大会堂',
    image: 'https://s.coze.cn/image/_MZe36hQ6ew/',
    description: '天安门广场西侧的国家议事殿堂，庄重大气。',
  },
  {
    id: 'badaling-great-wall',
    name: '八达岭长城',
    image: 'https://s.coze.cn/image/2J2ehK4A_Eo/',
    description: '北京最具代表性的长城段落，蜿蜒于燕山之间，雄伟壮观、闻名中外。',
  },
  {
    id: 'summer-palace',
    name: '颐和园',
    image: 'https://s.coze.cn/image/S3CAWf9rkN0/',
    description: '清代皇家园林典范，以昆明湖与万寿山为骨架，湖光山色。',
  },
  {
    id: 'old-summer-palace',
    name: '圆明园',
    image: 'https://s.coze.cn/image/N77LVuwC4Jo/',
    description: '清代大型皇家园林遗址，残存的大水法等遗迹见证近代历史沧桑。',
  },
  {
    id: 'temple-of-heaven',
    name: '天坛公园',
    image: 'https://s.coze.cn/image/z7fy7KdEUEs/',
    description: '明清帝王祭天祈谷之所，祈年殿为其标志性建筑。',
  },
  {
    id: 'jingshan-park',
    name: '景山公园',
    image: 'https://s.coze.cn/image/9zTqhhjGjzE/',
    description: '登万春亭可俯瞰故宫全景，是观景绝佳之地。',
  },
  {
    id: 'yonghegong',
    name: '雍和宫',
    image: 'https://s.coze.cn/image/OsPI5vq5IEU/',
    description: '北京规模最大的藏传佛教寺院，殿宇宏伟，香火鼎盛。',
  },
  {
    id: 'beihai-park',
    name: '北海公园',
    image: 'https://s.coze.cn/image/hf-uXNe3Rqg/',
    description: '保存最完整的古典皇家园林之一，白塔为湖畔标志。',
  },
  {
    id: 'prince-gong-mansion',
    name: '恭王府',
    image: 'https://s.coze.cn/image/hFfkjIUj7Eo/',
    description: '清代王府建筑群代表，素有「一座恭王府，半部清代史」之说。',
  },
  {
    id: 'shichahai',
    name: '什刹海',
    image: 'https://s.coze.cn/image/NiswyPtWUmg/',
    description: '传统胡同与水域交织的历史文化街区，京味浓郁。',
  },
  {
    id: 'nanluoguxiang',
    name: '南锣鼓巷',
    image: 'https://s.coze.cn/image/EH18fjbxJfg/',
    description: '北京最古老的街区之一，胡同文化与特色小店汇聚。',
  },
  {
    id: 'qianmen-street',
    name: '前门大街',
    image: 'https://s.coze.cn/image/tzA9kNYn1Ws/',
    description: '百年商业老街，老字号云集，京味十足。',
  },
  {
    id: 'birds-nest-water-cube',
    name: '鸟巢水立方',
    image: 'https://s.coze.cn/image/_0b2Cbm53Fo/',
    description: '2008 奥运会主场馆，建筑造型独特，是现代都市地标。',
  },
  {
    id: 'ditan-park',
    name: '地坛公园',
    image: 'https://s.coze.cn/image/Tc7G0q8UDOQ/',
    description: '明清帝王祭地之所，古柏森然、环境清幽。',
  },
  {
    id: 'ruc',
    name: '中国人民大学',
    image: 'https://s.coze.cn/image/_InYSyJL33c/',
    description: '人文社会科学领域著名高等学府。',
  },
  {
    id: 'tsinghua',
    name: '清华大学',
    image: 'https://s.coze.cn/image/dDV6HM26Pho/',
    description: '中国顶尖综合性大学，二校门与园林校园闻名。',
  },
  {
    id: 'pku',
    name: '北京大学',
    image: 'https://s.coze.cn/image/sb3U_bGARgA/',
    description: '中国著名高等学府，未名湖与博雅塔景致典雅。',
  },
  {
    id: 'wangfujing',
    name: '王府井',
    image: 'https://s.coze.cn/image/go88RelBi24/',
    description: '北京著名商业街，繁华购物与美食汇聚之地。',
  },
];